/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package grafic;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.eclipse.persistence.internal.oxm.mappings.Login;

/**
 *
 * @author alexa_000
 */
public class Administratorapp extends javax.swing.JFrame {

    /**
     * Creates new form Administratorapp
     */
    public Administratorapp() throws FileNotFoundException, IOException {
        
        int i;
       BufferedReader fisier;
       
        try {
            listModelSecretari = new DefaultListModel();
            listModelProfesori = new DefaultListModel();
            listModelElevi = new DefaultListModel();
            
            fisier = new BufferedReader(new FileReader("credentials"));
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            for(i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Secretar"))
                    listModelSecretari.addElement(vector.get(i));
                if(vector.get(i+4).equals("Profesor"))
                    listModelProfesori.addElement(vector.get(i));
                if(vector.get(i+4).equals("Elev"))
                    listModelElevi.addElement(vector.get(i));               
            }
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        BufferedReader fisier2 = new BufferedReader(new FileReader("clase"));
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier2.readLine())!= null;){
                vector.add(line);                  
            }
            for(int j=0;j<vector.size();j++)
                clasaDeSters.addItem(vector.get(j));
        BufferedReader fisier3 = new BufferedReader(new FileReader("fmaterii"));
        ArrayList<String> vector2 = new ArrayList<>();
        for(String line; (line = fisier3.readLine())!= null;){
                vector2.add(line);                  
        }
        for(int k=0;k<vector.size();k++)
                materieDeSters.addItem(vector2.get(k));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaugareClasa = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        numeClasa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        adaugareMaterie = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        materieDeAdaugat = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        clasaDeSters = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        materieDeSters = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        numecomplet = new javax.swing.JLabel();
        labelusernamesecretar = new javax.swing.JLabel();
        parolaSecretarlabel = new javax.swing.JLabel();
        ncSecretar = new javax.swing.JTextField();
        usernameSecretar = new javax.swing.JTextField();
        parolaSecretar = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cnpSecretar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaSecretari = new javax.swing.JList(listModelSecretari);
        jButton24 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        jLabel23 = new javax.swing.JLabel();
        ncProfesor = new javax.swing.JTextField();
        usernameProfesor = new javax.swing.JTextField();
        parolaProfesor = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cnpProfesor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaProfesori = new javax.swing.JList(listModelProfesori);
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        usernameElev = new javax.swing.JTextField();
        parolaElev = new javax.swing.JTextField();
        ncElev = new javax.swing.JTextField();
        cnpElev = new javax.swing.JTextField();
        clasaElev = new javax.swing.JComboBox();
        jButton15 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        listaElevi = new javax.swing.JList(listModelElevi);
        jButton16 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList();
        jButton17 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jTextField13 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox();
        jButton19 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList();
        jLabel34 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jButton21 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        adaugareClasa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adaugareClasa.setTitle("Adaugare Clasa");
        adaugareClasa.setAlwaysOnTop(true);
        adaugareClasa.setFocusable(false);
        adaugareClasa.setLocationByPlatform(true);
        adaugareClasa.setMinimumSize(new java.awt.Dimension(268, 83));
        adaugareClasa.setUndecorated(true);
        adaugareClasa.setResizable(false);
        adaugareClasa.setType(java.awt.Window.Type.POPUP);

        jLabel2.setText("Numele Clasei:");

        jButton3.setText("Adauga");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adaugareClasaLayout = new javax.swing.GroupLayout(adaugareClasa.getContentPane());
        adaugareClasa.getContentPane().setLayout(adaugareClasaLayout);
        adaugareClasaLayout.setHorizontalGroup(
            adaugareClasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adaugareClasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(numeClasa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adaugareClasaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        adaugareClasaLayout.setVerticalGroup(
            adaugareClasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adaugareClasaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adaugareClasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeClasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adaugareMaterie.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        adaugareMaterie.setTitle("Adaugare Materie");
        adaugareMaterie.setAlwaysOnTop(true);
        adaugareMaterie.setFocusable(false);
        adaugareMaterie.setLocationByPlatform(true);
        adaugareMaterie.setMinimumSize(new java.awt.Dimension(268, 83));
        adaugareMaterie.setUndecorated(true);
        adaugareMaterie.setResizable(false);
        adaugareMaterie.setType(java.awt.Window.Type.POPUP);

        jLabel5.setText("Numele Materiei:");

        jButton7.setText("Adauga");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adaugareMaterieLayout = new javax.swing.GroupLayout(adaugareMaterie.getContentPane());
        adaugareMaterie.getContentPane().setLayout(adaugareMaterieLayout);
        adaugareMaterieLayout.setHorizontalGroup(
            adaugareMaterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adaugareMaterieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adaugareMaterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adaugareMaterieLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(materieDeAdaugat, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adaugareMaterieLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap())
        );
        adaugareMaterieLayout.setVerticalGroup(
            adaugareMaterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adaugareMaterieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adaugareMaterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(materieDeAdaugat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setText("Bine ai venit "+login.user.getText()+" | Administrator");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 220, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 255, 255));
        jLabel37.setText("Welcome");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 200, 70));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 255, 255));
        jLabel38.setText(login.Name);
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 490, 60));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 255, 255));
        jLabel40.setText("Use tabs above to modify the various sections of the register!");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 450));

        jTabbedPane2.addTab("Home", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Add Class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 140, 50));

        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Materiile Clasei");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 80, -1));

        jButton2.setText("Delete Class");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 50));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Matematica", "Fizica", "Informatica" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 100, -1));

        jButton4.setText("Remove");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 100, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Romana", "Chimie", "Sport" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 120, -1));

        jButton5.setText("Add");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 120, 50));

        clasaDeSters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasaDeStersActionPerformed(evt);
            }
        });
        jPanel3.add(clasaDeSters, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, -1));

        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 450));

        jTabbedPane2.addTab("Classes", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Add Subject");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 150, 50));

        jButton8.setText("Delete Subject");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 50));

        jPanel4.add(materieDeSters, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        jTabbedPane2.addTab("Subjects", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numecomplet.setForeground(new java.awt.Color(204, 255, 255));
        numecomplet.setText("Full Name");
        jPanel1.add(numecomplet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        labelusernamesecretar.setForeground(new java.awt.Color(204, 255, 255));
        labelusernamesecretar.setText("Username");
        jPanel1.add(labelusernamesecretar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        parolaSecretarlabel.setForeground(new java.awt.Color(204, 255, 255));
        parolaSecretarlabel.setText("Password");
        jPanel1.add(parolaSecretarlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel1.add(ncSecretar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, -1));
        jPanel1.add(usernameSecretar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, -1));
        jPanel1.add(parolaSecretar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 110, -1));

        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("CNP");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel1.add(cnpSecretar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane7.addTab("Add", jPanel1);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaSecretari.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane5.setViewportView(listaSecretari);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        jButton24.setText("Stergere Secretar Ales");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane7.addTab("List", jPanel6);

        jTabbedPane2.addTab("Secretaries", jTabbedPane7);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(204, 255, 255));
        jLabel19.setText("Full Name");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("Username");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel21.setForeground(new java.awt.Color(204, 255, 255));
        jLabel21.setText("Password");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel22.setForeground(new java.awt.Color(204, 255, 255));
        jLabel22.setText("Subject");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Matematica", "Fizica", "Chimie", "Informatica", "Sport", "Roamana", "Geografie" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList6);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 150));

        jLabel23.setForeground(new java.awt.Color(204, 255, 255));
        jLabel23.setText("Classes:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
        jPanel7.add(ncProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, -1));
        jPanel7.add(usernameProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 160, -1));
        jPanel7.add(parolaProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9A", "9B", "9C", "9D", "10A" }));
        jPanel7.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, -1));

        jButton11.setText("Adauga");
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jList7.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "10D", "11C" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList7);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 100, -1));

        jButton12.setText("Remove");
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 100, -1));

        jButton13.setText("Add Teacher");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, 40));

        jLabel17.setForeground(new java.awt.Color(204, 255, 255));
        jLabel17.setText("CNP");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel7.add(cnpProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jTabbedPane8.addTab("Add", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setText("Delete Selected Teacher");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 220, 60));

        jScrollPane4.setViewportView(listaProfesori);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 330));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jTabbedPane8.addTab("Modify", jPanel8);

        jTabbedPane2.addTab("Teachers", jTabbedPane8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Username");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Password");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Full Name");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel24.setForeground(new java.awt.Color(204, 255, 255));
        jLabel24.setText("CNP");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel26.setForeground(new java.awt.Color(204, 255, 255));
        jLabel26.setText("Class");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel9.add(usernameElev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 140, -1));
        jPanel9.add(parolaElev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 140, -1));
        jPanel9.add(ncElev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, -1));
        jPanel9.add(cnpElev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        clasaElev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9A", "9B", "9C", "9D", "10A" }));
        jPanel9.add(clasaElev, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jButton15.setText("Add Student");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 120, 50));

        jScrollPane10.setViewportView(listaElevi);

        jPanel9.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 140, 150));

        jButton16.setText("Delete Student");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 140, 40));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jTabbedPane9.addTab("User Panel", jPanel9);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setForeground(new java.awt.Color(204, 255, 255));
        jLabel27.setText("Student");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jList9.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(jList9);

        jPanel12.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, 160));

        jButton17.setText("Choose");
        jPanel12.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel28.setForeground(new java.awt.Color(204, 255, 255));
        jLabel28.setText("Subject");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel30.setForeground(new java.awt.Color(204, 255, 255));
        jLabel30.setText("Class");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9A", "9B", "9C", "9D", "10A", " " }));
        jPanel12.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fizica", "Chimie", "Romana" }));
        jPanel12.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, -1));
        jPanel12.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 50, -1));

        jLabel31.setForeground(new java.awt.Color(204, 255, 255));
        jLabel31.setText("Grade");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jButton18.setText("Add");
        jPanel12.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 70, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "9", "5" }));
        jPanel12.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 50, -1));

        jButton19.setText("Delete");
        jPanel12.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 70, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jTabbedPane9.addTab("Grades", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9A", "9B", "9C", "9D", "10A", " " }));
        jPanel13.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel32.setForeground(new java.awt.Color(204, 255, 255));
        jLabel32.setText("Class");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jList10.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(jList10);

        jPanel13.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, 160));

        jLabel34.setForeground(new java.awt.Color(204, 255, 255));
        jLabel34.setText("Student");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jButton20.setText("Choose");
        jPanel13.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel35.setForeground(new java.awt.Color(204, 255, 255));
        jLabel35.setText("Subject");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fizica", "Chimie", "Romana" }));
        jPanel13.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, -1));

        jButton21.setText("Add Absence");
        jPanel13.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 150, -1));

        jList11.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(jList11);

        jPanel13.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 150, 150));

        jButton22.setText("Delete Absence");
        jPanel13.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, -1));

        jButton23.setText("Motivate Absence");
        jPanel13.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\books (1).jpg")); // NOI18N
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        jTabbedPane9.addTab("Absences", jPanel13);

        jTabbedPane2.addTab("Students", jTabbedPane9);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 480));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\img_CS\\emergency-exit-icon-10277712.jpg")); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adaugareClasa.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        adaugareClasa.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            // TODO add your handling code here:
            liceu.Secretar s = new liceu.Secretar(numeClasa.getText());
        try {
            s.addClasa();
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        clasaDeSters.removeAllItems();
        BufferedReader fisier;
        try {
            ArrayList<String> vector = new ArrayList<>();
            fisier = new BufferedReader(new FileReader("clase"));
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            for(int i=0;i<vector.size();i++)
                clasaDeSters.addItem(vector.get(i));
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        clasaDeSters.removeAllItems();
        BufferedReader fisier2;
        try {
            ArrayList<String> vector = new ArrayList<>();
            fisier2 = new BufferedReader(new FileReader("clase"));
            for(String line; (line = fisier2.readLine())!= null;){
                vector.add(line);                  
            }
            for(int i=0;i<vector.size();i++)
                clasaDeSters.addItem(vector.get(i));          
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        adaugareClasa.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        liceu.Administrator admin = new liceu.Administrator();
        try {
            admin.addMaterie(materieDeAdaugat.getText());
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        materieDeSters.removeAllItems();
        BufferedReader fisier2;
        try {
            ArrayList<String> vector = new ArrayList<>();
            fisier2 = new BufferedReader(new FileReader("fmaterii"));
            for(String line; (line = fisier2.readLine())!= null;){
                vector.add(line);                  
            }
            for(int i=0;i<vector.size();i++)
                materieDeSters.addItem(vector.get(i));          
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        adaugareMaterie.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        adaugareMaterie.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        adaugareMaterie.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        liceu.Administrator admin = new liceu.Administrator(usernameSecretar.getText(), parolaSecretar.getText(),ncSecretar.getText(),cnpSecretar.getText(),"Secretar");
        admin.addUser();
        usernameSecretar.setText("");
        parolaSecretar.setText("");
        ncSecretar.setText("");
        cnpSecretar.setText("");
        
        int i;
        BufferedReader fisier;
        try {
            fisier = new BufferedReader(new FileReader("credentials"));
            listModelSecretari.clear();
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }            
            for(i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Secretar"))
                   listModelSecretari.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        liceu.Administrator admin = new liceu.Administrator(usernameProfesor.getText(), parolaProfesor.getText(),ncProfesor.getText(),cnpProfesor.getText(),"Profesor");
        admin.addUser();
        usernameProfesor.setText("");
        parolaProfesor.setText("");
        ncProfesor.setText("");
        cnpProfesor.setText("");
        
        int i;
        BufferedReader fisier;
        try {
            fisier = new BufferedReader(new FileReader("credentials"));
            listModelProfesori.clear();
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }            
            for(i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Profesor"))
                   listModelProfesori.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        liceu.Administrator admin = new liceu.Administrator(usernameElev.getText(), parolaElev.getText(),ncElev.getText(),cnpElev.getText(),"Elev",(String)clasaElev.getSelectedItem());
        admin.addUser();
        usernameElev.setText("");
        parolaElev.setText("");
        ncElev.setText("");
        cnpElev.setText("");
        
        int i;
        BufferedReader fisier;
        try {
            fisier = new BufferedReader(new FileReader("credentials"));
            listModelElevi.clear();
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }            
            for(i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Elev"))
                   listModelElevi.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        String s = (String) listaSecretari.getSelectedValue();
        liceu.Administrator admin = new liceu.Administrator();
        admin.delUser(s);
        BufferedReader fisier;
        try {            
            fisier = new BufferedReader(new FileReader("credentials"));
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }                   
            listModelSecretari.clear();
            for(int i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Secretar"))
                    listModelSecretari.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String s = (String) listaProfesori.getSelectedValue();
        liceu.Administrator admin = new liceu.Administrator();
        admin.delUser(s);
        
        BufferedReader fisier;        
        try {            
            fisier = new BufferedReader(new FileReader("credentials"));
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            listModelProfesori.clear();
            for(int i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Profesor"))
                    listModelProfesori.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        String s = (String) listaElevi.getSelectedValue();
        liceu.Administrator admin = new liceu.Administrator();
        admin.delUser(s);
        
        BufferedReader fisier;        
        try {            
            fisier = new BufferedReader(new FileReader("credentials"));
            ArrayList<String> vector = new ArrayList<>();
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            listModelElevi.clear();
            for(int i=0;i<vector.size();i=i+5){
                if(vector.get(i+4).equals("Elev"))
                    listModelElevi.addElement(vector.get(i));
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void clasaDeStersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasaDeStersActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clasaDeStersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        liceu.Secretar s = new liceu.Secretar();
        s.delClasa((String)clasaDeSters.getSelectedItem());
        clasaDeSters.removeAllItems();
        BufferedReader fisier;
        try {
            ArrayList<String> vector = new ArrayList<>();
            fisier = new BufferedReader(new FileReader("clase"));
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            for(int i=0;i<vector.size();i++)
                clasaDeSters.addItem(vector.get(i));
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        liceu.Administrator admin = new liceu.Administrator();
        admin.delMaterie((String)materieDeSters.getSelectedItem());
        materieDeSters.removeAllItems();
        BufferedReader fisier;
        try {
            ArrayList<String> vector = new ArrayList<>();
            fisier = new BufferedReader(new FileReader("fmaterii"));
            for(String line; (line = fisier.readLine())!= null;){
                vector.add(line);                  
            }
            for(int i=0;i<vector.size();i++)
                materieDeSters.addItem(vector.get(i));
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Secretarapp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administratorapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administratorapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administratorapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administratorapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administratorapp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Administratorapp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame adaugareClasa;
    private javax.swing.JFrame adaugareMaterie;
    private javax.swing.JComboBox clasaDeSters;
    private javax.swing.JComboBox clasaElev;
    private javax.swing.JTextField cnpElev;
    private javax.swing.JTextField cnpProfesor;
    private javax.swing.JTextField cnpSecretar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList10;
    private javax.swing.JList jList11;
    private javax.swing.JList jList2;
    private javax.swing.JList jList6;
    private javax.swing.JList jList7;
    private javax.swing.JList jList9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JLabel labelusernamesecretar;
    private javax.swing.JList listaElevi;
    private javax.swing.JList listaProfesori;
    private javax.swing.JList listaSecretari;
    private javax.swing.JTextField materieDeAdaugat;
    private javax.swing.JComboBox materieDeSters;
    private javax.swing.JTextField ncElev;
    private javax.swing.JTextField ncProfesor;
    private javax.swing.JTextField ncSecretar;
    public javax.swing.JTextField numeClasa;
    private javax.swing.JLabel numecomplet;
    private javax.swing.JTextField parolaElev;
    private javax.swing.JTextField parolaProfesor;
    private javax.swing.JTextField parolaSecretar;
    private javax.swing.JLabel parolaSecretarlabel;
    private javax.swing.JTextField usernameElev;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameProfesor;
    private javax.swing.JTextField usernameSecretar;
    // End of variables declaration//GEN-END:variables
    public static DefaultListModel listModelSecretari;
    public static DefaultListModel listModelProfesori;
    public static DefaultListModel listModelElevi;
}
